# -*- mode:snakemake; -*-
from snakemake.utils import min_version

min_version("6.0")


configfile: "config/general_config.yml"  # Path to config file containing general variables, relative to the workflow folder


module ase_idpp:
    snakefile:
        "rules/ase_idpp.smk"
    config:
        config["common"]


module get_petmad:
    snakefile:
        "rules/get_petmad.smk"


use rule * from ase_idpp as __ase_idpp_*


use rule * from get_petmad


rule doneb:
    input:
        expand("results/pet-mad-{version}.pt", version=config["pet_mad"]["version"]),
    output:
        "results/plots/.gitkeep",
    run:
        shell("mkdir -p results/plots && touch results/plots/.gitkeep")


rule all:
    input:
        rules.__ase_idpp_collect_paths.output,
        "results/plots/.gitkeep",
    default_target: True
