# -*- mode:snakemake; -*-
from snakemake.utils import min_version

min_version("6.0")


configfile: "config/general_config.yml"  # Path to config file containing general variables, relative to the workflow folder


module ase_idpp:
    snakefile:
        "rules/ase_idpp.smk"
    config:
        config["common"]


module get_petmad:
    snakefile:
        "rules/get_petmad.smk"


module run_eon:
    snakefile:
        "rules/run_eon.smk"
    config:
        config


module plotting:
    snakefile:
        "rules/plotting.smk"
    config:
        config


use rule * from ase_idpp as __ase_idpp_*


use rule * from get_petmad


use rule * from run_eon


use rule plot_neb_path from plotting


rule all:
    input:
        rules.plot_neb_path.output,
    default_target: True
