[workspace]
authors = ["Rohit Goswami <rohit.goswami@epfl.ch>"]
channels = ["metatensor", "https://repo.prefix.dev/rg-forge", "conda-forge", "bioconda"]
name = "metatensor_ecosystem_paper"
platforms = ["linux-64"]
version = "0.1.0"

[tasks.dag]
args = ["_cwd"]
cmd = "cd {{ _cwd }} && snakemake -F --dag | dot -Tsvg > resources/dag.svg"

[tasks.rulegraph]
args = ["_cwd"]
cmd = "cd {{ _cwd }} && snakemake -F --rulegraph | dot -Tsvg > resources/rulegraph.svg"

[tasks.filegraph]
args = ["_cwd"]
cmd = "cd {{ _cwd }} && snakemake -F --filegraph | dot -Tsvg > resources/filegraph.svg"

[tasks.graphs]
args = ["_cwd"]
depends-on = [
  { task = "dag", args = ["{{ _cwd }}"] },
  { task = "rulegraph", args = ["{{ _cwd }}"] },
  { task = "filegraph", args = ["{{ _cwd }}"] },
]

[tasks.all-graphs]
depends-on = [
  { task = "graphs", environment = "eon", args = ["metatensor_integrations/eon"] },
]

[dependencies]
python = ">=3.12.5,<3.13"
snakemake = ">=9.10.1,<10"
uv = ">=0.8.15,<0.9"

[pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cpu"]

[pypi-dependencies]
metatrain = ">=2025.8.1, <2026"
metatensor-torch = ">=0.7.6, <0.8"
metatomic-torch = ">=0.1.3, <0.2"
ase = ">=3.25.0, <4"
rgpycrumbs = "==0.0.2"

[feature.eon.dependencies]
eigen = ">=3.4.0,<4"
cmake = ">=4.0.3,<5"
highfive = ">=2.10.1,<3"
meson = ">=1.8.2,<2"
ninja = ">=1.13.1,<2"
pkgconf = ">=2.5.1,<3"
openblas = ">=0.3.30,<0.4"
compilers = ">=1.10.0,<2"
gfortran = ">=13.3.0,<13.4"
fmt = ">=11.2.0,<12"
spdlog = ">=1.15.3,<2"
eon = ">=2.8.0,<3"

[feature.plumed.pypi-dependencies]
chemiscope = ">=0.8.6, <0.9"

[feature.plumed.dependencies]
lammps-metatomic = { version = "*", build = "*openmpi*" }
plumed-metatomic = { version = "*", build = "*openmpi*" }

[feature.r-analysis.dependencies]
r = ">=4.4,<4.5"

[feature.r-analysis.pypi-dependencies]
radian = ">=0.6.15, <0.7"

[environments]
eon = {features = ["eon"]}
plumed = {features = ["plumed"]}
r-analysis = {features = ["r-analysis"]}
